/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthResetPasswordRequestRouteImport } from './routes/_auth/reset-password-request'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppFollowsRouteImport } from './routes/_app/follows'
import { Route as AppThreadsThreadIdRouteImport } from './routes/_app/threads.$threadId'
import { Route as AppProfileUserIdRouteImport } from './routes/_app/profile.$userId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthResetPasswordRequestRoute =
  AuthResetPasswordRequestRouteImport.update({
    id: '/reset-password-request',
    path: '/reset-password-request',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowsRoute = AppFollowsRouteImport.update({
  id: '/follows',
  path: '/follows',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadsThreadIdRoute = AppThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppProfileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/follows': typeof AppFollowsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/search': typeof AppSearchRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password-request': typeof AuthResetPasswordRequestRoute
  '/': typeof AppIndexRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
}
export interface FileRoutesByTo {
  '/follows': typeof AppFollowsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/search': typeof AppSearchRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password-request': typeof AuthResetPasswordRequestRoute
  '/': typeof AppIndexRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/follows': typeof AppFollowsRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/search': typeof AppSearchRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password-request': typeof AuthResetPasswordRequestRoute
  '/_app/': typeof AppIndexRoute
  '/_app/profile/$userId': typeof AppProfileUserIdRoute
  '/_app/threads/$threadId': typeof AppThreadsThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/follows'
    | '/profile'
    | '/search'
    | '/login'
    | '/register'
    | '/reset-password-request'
    | '/'
    | '/profile/$userId'
    | '/threads/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/follows'
    | '/profile'
    | '/search'
    | '/login'
    | '/register'
    | '/reset-password-request'
    | '/'
    | '/profile/$userId'
    | '/threads/$threadId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/follows'
    | '/_app/profile'
    | '/_app/search'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password-request'
    | '/_app/'
    | '/_app/profile/$userId'
    | '/_app/threads/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/reset-password-request': {
      id: '/_auth/reset-password-request'
      path: '/reset-password-request'
      fullPath: '/reset-password-request'
      preLoaderRoute: typeof AuthResetPasswordRequestRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follows': {
      id: '/_app/follows'
      path: '/follows'
      fullPath: '/follows'
      preLoaderRoute: typeof AppFollowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threads/$threadId': {
      id: '/_app/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof AppThreadsThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$userId': {
      id: '/_app/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppProfileRoute
    }
  }
}

interface AppProfileRouteChildren {
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileUserIdRoute: AppProfileUserIdRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppFollowsRoute: typeof AppFollowsRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppThreadsThreadIdRoute: typeof AppThreadsThreadIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFollowsRoute: AppFollowsRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppThreadsThreadIdRoute: AppThreadsThreadIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRequestRoute: typeof AuthResetPasswordRequestRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRequestRoute: AuthResetPasswordRequestRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
